version: '3.6'
services:
  discordbot:
    image: disocrd.bot
    container_name: discord-bot-container
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/root/python-projects/discord_bot
    networks:
      - lb_net


networks:
  lb_net:
    name: lb_net
    external: true
